In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
df1 = pd.read_csv('Data/In-lab/P2/processed.csv')

df1.head()

,Start,End,mean,standard deviation,min,max,median,mode,skew,Kurtosis,...,RMSSD,nn50,nn20,SDSD,zcross,Lf,MF,HF,Lf/HF,Count
0,1.501799e+12,1.501799e+12,643.010870,37.130058,533.0,784.0,647.0,645.0,-0.352298,2.387338,...,20.040892,2,16,15.437077,16,65.989130,57.847826,57.641304,1.144824,0.985950
1,1.501799e+12,1.501799e+12,643.700000,21.382469,601.0,692.0,645.0,645.0,-0.257383,-0.675181,...,11.790790,0,7,6.921490,17,65.677778,65.277778,64.733333,1.014590,0.965550
2,1.501799e+12,1.501799e+12,634.559140,27.123954,569.0,689.0,636.0,629.0,-0.180472,-0.526052,...,12.447280,0,9,6.950303,12,61.537634,63.043011,66.311828,0.928004,0.983567
3,1.501799e+12,1.501799e+12,644.032609,38.117510,569.0,740.0,641.0,645.0,0.099792,-0.626869,...,17.043577,1,12,10.824538,15,60.641304,63.728261,64.119565,0.945754,0.987517
4,1.501799e+12,1.501799e+12,671.534091,39.125076,573.0,748.0,676.5,673.0,-0.424185,-0.475887,...,16.631918,0,14,9.625996,12,63.204545,62.534091,70.352273,0.898401,0.984917

In [14]:
df1.columns

Index(['Start', 'End', 'mean', 'standard deviation', 'min', 'max', 'median',
       'mode', 'skew', 'Kurtosis', '80_percentile', '60_percentile',
       '40_percentile', '20_percentile', 'RMS', 'IQR', 'count>mean',
       'count<mean', 'range', 'COV_M', 'pNN50', 'pNN20', 'RMSSD', 'nn50',
       'nn20', 'SDSD', 'zcross', 'Lf', 'MF', 'HF', 'Lf/HF', 'Count'],
      dtype='object')

In [15]:
df2 = pd.read_csv('Data/In-lab/P2/labeledfeatures.csv')

df2.head()

,Start,End,mean,standard deviation,min,max,median,mode,skew,Kurtosis,...,Did you feel things are going your way?,Did you feel difficulties piling up so you cannot overcome them?,How happy were you feeling?,How excited were you feeling?,How content were you feeling?,How worried were you feeling?,How irritable/angry were you feeling?,How sad were you feeling?,PSS,Induction
0,1.501799e+12,1.501799e+12,642.677419,35.033981,549.0,744.0,649.0,649.0,-0.704955,1.048043,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
1,1.501799e+12,1.501799e+12,643.804348,20.960231,601.0,696.0,646.5,657.0,-0.270409,-0.535923,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
2,1.501799e+12,1.501799e+12,634.559140,27.031826,569.0,689.0,636.0,645.0,-0.189439,-0.479813,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
3,1.501799e+12,1.501799e+12,644.032609,37.691958,569.0,740.0,645.0,645.0,0.142098,-0.518607,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
4,1.501799e+12,1.501799e+12,671.191011,39.249956,569.0,744.0,677.0,673.0,-0.413178,-0.523558,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2

In [16]:
df2.columns

Index(['Start', 'End', 'mean', 'standard deviation', 'min', 'max', 'median',
       'mode', 'skew', 'Kurtosis', '80_percentile', '60_percentile',
       '40_percentile', '20_percentile', 'RMS', 'IQR', 'count>mean',
       'count<mean', 'range', 'COV_M', 'pNN50', 'pNN20', 'RMSSD', 'nn50',
       'nn20', 'SDSD', 'zcross', 'Lf', 'MF', 'HF', 'Lf/HF', 'Count',
       'EventType', 'Did you experience anything stressful?',
       'How stressed were you feeling?',
       'Did you feel you could not control important things?',
       'Did you feel confident in your ability to handle problems?',
       'Did you feel things are going your way?',
       'Did you feel difficulties piling up so you cannot overcome them?',
       'How happy were you feeling?', 'How excited were you feeling?',
       'How content were you feeling?', 'How worried were you feeling?',
       'How irritable/angry were you feeling?', 'How sad were you feeling?',
       'PSS', 'Induction'],
      dtype='object')

In [18]:
df1.shape, df2.shape

((199, 32), (199, 47))

In [19]:
df3 = pd.read_csv('Data/In-lab/P2/annotations.csv')

df3.head()

,Timestamp (ms),AnnotationId,EventType,AuthorId,Start Timestamp (ms),Stop Timestamp (ms),Value
0,1501799616038,Activity:Prepare Speech,Prepare Speech,Kristen Rosen,1501799315700,1501799615714,NaN
1,1501799960460,Activity:Speech,Speech,Kristen Rosen,1501799659961,1501799959972,NaN
2,1501800334014,Activity:Arithmetic,Arithmetic,Kristen Rosen,1501800033653,1501800333666,NaN
3,1501800810825,Activity:Rest- TSST,Rest- TSST,Kristen Rosen,1501800510343,1501800810347,NaN
4,1501800929725,Activity:Ice Bucket 6,Ice Bucket 6,Kristen Rosen,1501800863108,1501800926728,NaN

In [20]:
df3.columns

Index(['Timestamp (ms)', 'AnnotationId', 'EventType', 'AuthorId',
       'Start Timestamp (ms)', 'Stop Timestamp (ms)', 'Value'],
      dtype='object')

In [21]:
df3.shape

(21, 7)

In [35]:
df3['AnnotationId']

0            Activity:Prepare Speech
1                    Activity:Speech
2                Activity:Arithmetic
3                Activity:Rest- TSST
4              Activity:Ice Bucket 6
5                     Activity:rest1
6                  Activity:Stroop 2
7                     Activity:rest2
8     Activity:Social Conversation 5
9                     Activity:rest3
10                  Activity:Cry 7-1
11                Activity:cry-rest1
12                  Activity:Cry 7-2
13                Activity:cry-rest2
14                  Activity:Cry 7-3
15                    Activity:rest4
16            Activity:sing-a-song 1
17                    Activity:rest5
18                   Activity:Game 4
19                    Activity:rest6
20                 Activity:Eating 3
Name: AnnotationId, dtype: object

In [36]:
start, end = df3['Start Timestamp (ms)'].to_numpy(), df3['Stop Timestamp (ms)'].to_numpy()

(end-start) / 60000

array([5.00023333, 5.00018333, 5.00021667, 5.00006667, 1.06033333,
       3.00016667, 4.00006667, 3.00015   , 4.00006667, 3.00003333,
       0.66683333, 3.0002    , 0.66676667, 3.00003333, 0.6669    ,
       3.00016667, 4.00021667, 3.00011667, 4.00005   , 3.00018333,
       4.00025   ])

In [42]:
df2

,Start,End,mean,standard deviation,min,max,median,mode,skew,Kurtosis,...,Did you feel things are going your way?,Did you feel difficulties piling up so you cannot overcome them?,How happy were you feeling?,How excited were you feeling?,How content were you feeling?,How worried were you feeling?,How irritable/angry were you feeling?,How sad were you feeling?,PSS,Induction
0,1.501799e+12,1.501799e+12,642.677419,35.033981,549.0,744.0,649.0,649.0,-0.704955,1.048043,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
1,1.501799e+12,1.501799e+12,643.804348,20.960231,601.0,696.0,646.5,657.0,-0.270409,-0.535923,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
2,1.501799e+12,1.501799e+12,634.559140,27.031826,569.0,689.0,636.0,645.0,-0.189439,-0.479813,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
3,1.501799e+12,1.501799e+12,644.032609,37.691958,569.0,740.0,645.0,645.0,0.142098,-0.518607,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
4,1.501799e+12,1.501799e+12,671.191011,39.249956,569.0,744.0,677.0,673.0,-0.413178,-0.523558,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,1.501804e+12,1.501804e+12,625.115789,28.238780,560.0,693.0,621.0,613.0,0.165540,-0.242888,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
195,1.501804e+12,1.501804e+12,626.250000,36.429093,560.0,781.0,618.5,613.0,1.200550,2.656756,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
196,1.501804e+12,1.501804e+12,644.752809,36.789801,573.0,781.0,645.0,613.0,0.621024,0.926943,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
197,1.501804e+12,1.501805e+12,662.288889,35.079353,581.0,749.0,659.0,657.0,0.370146,0.178788,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
198,1.501804e+12,1.501805e+12,696.200000,38.801698,605.0,761.0,693.0,665.0,-0.254912,-0.764150,...,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2

In [57]:
df2['EventType'].unique()

array([nan, 'TSST_prep', 'TSST_speech', 'TSST_mentalSub', 'IceBucket',
       'Rest1', 'Stroop', 'Rest2', 'SocialCon', 'Rest3', 'InfantCrying',
       'Rest4', 'Sing-a-song', 'Rest5', 'Game', 'Rest6', 'Eating'],
      dtype=object)

In [54]:
activities = df2[~df2['EventType'].isna()]['EventType'].unique()
ema_questions = ['Did you experience anything stressful?',
       'How stressed were you feeling?',
       'Did you feel you could not control important things?',
       'Did you feel confident in your ability to handle problems?',
       'Did you feel things are going your way?',
       'Did you feel difficulties piling up so you cannot overcome them?',
       'How happy were you feeling?', 'How excited were you feeling?',
       'How content were you feeling?', 'How worried were you feeling?',
       'How irritable/angry were you feeling?', 'How sad were you feeling?',
       'PSS', 'Induction']

df2[df2['EventType']==activities[0]].iloc[0][ema_questions].to_numpy()

array([1.0, 3.0, 3.0, 3.0, 3.0, 2.0, 10.0, 20.0, 10.0, 50.0, 10.0, 10.0,
       11.0, 1], dtype=object)

In [43]:
df2[df2['Induction']!=-2]

,Start,End,mean,standard deviation,min,max,median,mode,skew,Kurtosis,...,Did you feel things are going your way?,Did you feel difficulties piling up so you cannot overcome them?,How happy were you feeling?,How excited were you feeling?,How content were you feeling?,How worried were you feeling?,How irritable/angry were you feeling?,How sad were you feeling?,PSS,Induction
25,1.501799e+12,1.501799e+12,618.126316,47.395368,512.0,757.0,621.0,621.0,-0.151005,0.196901,...,3.0,2.0,10.0,20.0,10.0,50.0,10.0,10.0,11.0,1
26,1.501799e+12,1.501799e+12,641.153846,27.667541,589.0,757.0,637.0,621.0,1.014440,2.380508,...,3.0,2.0,10.0,20.0,10.0,50.0,10.0,10.0,11.0,1
27,1.501799e+12,1.501799e+12,630.739130,24.947279,589.0,705.0,630.5,637.0,0.399481,-0.092872,...,3.0,2.0,10.0,20.0,10.0,50.0,10.0,10.0,11.0,1
28,1.501799e+12,1.501799e+12,621.670213,27.417725,557.0,705.0,625.0,625.0,0.238160,0.430927,...,3.0,2.0,10.0,20.0,10.0,50.0,10.0,10.0,11.0,1
29,1.501799e+12,1.501799e+12,629.680851,35.901228,557.0,737.0,625.0,625.0,0.562693,0.316553,...,3.0,2.0,10.0,20.0,10.0,50.0,10.0,10.0,11.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,1.501804e+12,1.501804e+12,638.548387,27.209469,589.0,709.0,637.0,645.0,0.330842,-0.591340,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
194,1.501804e+12,1.501804e+12,625.115789,28.238780,560.0,693.0,621.0,613.0,0.165540,-0.242888,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
195,1.501804e+12,1.501804e+12,626.250000,36.429093,560.0,781.0,618.5,613.0,1.200550,2.656756,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
196,1.501804e+12,1.501804e+12,644.752809,36.789801,573.0,781.0,645.0,613.0,0.621024,0.926943,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0
197,1.501804e+12,1.501805e+12,662.288889,35.079353,581.0,749.0,659.0,657.0,0.370146,0.178788,...,4.0,0.0,50.0,40.0,60.0,0.0,0.0,0.0,3.0,0

In [38]:
(start[1:] - end[:-1]) / 60000

array([0.73745   , 1.22801667, 2.94461667, 0.87935   , 1.05205   ,
       1.13446667, 0.70083333, 0.88853333, 0.94365   , 1.07205   ,
       0.19251667, 0.42048333, 0.12735   , 0.2461    , 2.89366667,
       0.66495   , 0.90976667, 1.04778333, 0.78688333, 0.84066667])

In [23]:
df4 = pd.read_csv('Data/In-lab/P2/elec.csv')

df4.head()

   Timestamp (ms)  Sample (V)
0   1501798559062    0.022030
1   1501798559066    0.013832
2   1501798559070    0.010146
3   1501798559074    0.008250
4   1501798559078    0.007690

In [24]:
df4.shape

(1501942, 2)

In [27]:
df4.shape[0]/6000

250.32366666666667

In [26]:
df4.describe()

       Timestamp (ms)    Sample (V)
count    1.501942e+06  1.501942e+06
mean     1.501802e+12  4.694328e-03
std      1.736865e+06  2.445378e-04
min      1.501799e+12 -6.963785e-03
25%      1.501800e+12  4.618931e-03
50%      1.501802e+12  4.705094e-03
75%      1.501803e+12  4.772793e-03
max      1.501805e+12  2.667041e-02